---
- hosts: localhost
  vars:
  - warName: sample.war
  - warRemotePath: /var/lib/tomcat7/webapps

  tasks:
  - name: Download WAR to server
    command: wget https://github.com/shanuantony/KTfromJibin/blob/master/sample.war -O {{ warRemotePath }}/{{ warName }}
  
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/var/lib/tomcat7/webapps/ copy=no mode=0755 owner=tomcat7 group=tomcat7
    notify:
        - restart tomcat7
   
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat7
      service: name=tomcat7 state=restarted
